/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(ofdm_synchronization_gpu.h) */
/* BINDTOOL_HEADER_FILE_HASH(4cbc8b422309e33feb32fda0e23ce33a) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/isdbt/ofdm_synchronization_gpu.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_synchronization_gpu_pydoc.h>

void bind_ofdm_synchronization_gpu(py::module &m) {

  using ofdm_synchronization_gpu = ::gr::isdbt::ofdm_synchronization_gpu;

  py::class_<ofdm_synchronization_gpu, gr::block, gr::basic_block,
             std::shared_ptr<ofdm_synchronization_gpu>>(m, "ofdm_synchronization_gpu",
                                                    D(ofdm_synchronization_gpu))

      .def(py::init(&ofdm_synchronization_gpu::make), py::arg("mode"),
           py::arg("cp_length"), py::arg("interpolate"),
           D(ofdm_synchronization_gpu, make))

      ;
}
